name: test moving issues for contribution

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test-issue-contribution:
    runs-on: ubuntu-latest
    steps:
      - uses: allisonport-db/github-project-automation-plus@main
        with:
          project: test github actions
          column: Backlog
          repo-token: ${{ secrets.TEST_PR_AUTOMATION }}
