name: Move updated PR to needs review

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]
  
jobs:
  automate-updated-pull-requests:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test github actions
          column: needs review
          repo-token: ${{ secrets.TEST_PR_AUTOMATION }}
