name: Move updated PR to needs review

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]
  
jobs:
  automate-updated-pull-requests:
    if: ${{ github.event.issue.pull_request || github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: allisonport-db/github-project-automation-plus@a8cbe340e2daba9f6a7ba8e185658e7a342f3b3d
        with:
          project: test github actions
          column: needs review
          repo-token: ${{ secrets.TEST_PR_AUTOMATION }}
