name: Move updated PR to needs review

env:
  usernames: test

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]
  pull_request_review_comment:
    types: [created]

jobs:
  automate-updated-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@2af3cf061aeca8ac6ab40a960eee1968a7f9ce0e
        if: ${{ (github.event.issue.pull_request || github.event.pull_request) && !contains(env.usernames, github.event.sender.login) &&
            (github.event.pull_request.state == 'open' || github.event.issue.state == 'open') }}
        with:
          project: test github actions
          column: needs review
          repo-token: ${{ secrets.TEST_PR_AUTOMATION }}
