name: Move updated PR to needs review

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]
  
jobs:
  automate-updated-pull-requests:
    if: ${{ !contains(["dennyglee", "scottsand-db", "tdas", "zsxwing"], github.event.actor.login) }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@2af3cf061aeca8ac6ab40a960eee1968a7f9ce0e
        if: ${{ github.event.issue.pull_request || github.event.pull_request }}
        with:
          project: test github actions
          column: needs review
          repo-token: ${{ secrets.TEST_PR_AUTOMATION }}
